apiVersion: apps/v1
kind: Deployment
metadata:
  name: admin-frontend
  namespace: cybericebox
  labels:
    app: admin-frontend
spec:
  replicas: 1
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 3
      maxUnavailable: 0
  selector:
    matchLabels:
      app: admin-frontend
  template:
    metadata:
      name: event-frontend
      namespace: cybericebox
      labels:
        app: admin-frontend
    spec:
      containers:
        - name: admin-frontend
          image: cybericebox/admin-frontend:latest
          env:
            - name: NEXT_PUBLIC_DOMAIN
              valueFrom:
                configMapKeyRef:
                  name: config
                  key: DOMAIN
          ports:
            - containerPort: 3000
              protocol: TCP
          resources:
            requests:
              memory: "64Mi"
              cpu: "100m"
            limits:
              memory: "128Mi"
              cpu: "200m"
          readinessProbe:
            httpGet:
              port: 3000
              path: /api/health
            initialDelaySeconds: 20
          livenessProbe:
            httpGet:
              port: 3000
              path: /api/health
            initialDelaySeconds: 20
            periodSeconds: 30