/**
 * versions.ts — exercise versions/lifecycle and draft snapshot types.
 *
 * Routes: GET /api/exercises/:id/versions[/:versionID],
 *   POST :id/versions/:versionID/rollback, PUT/DELETE :id/draft, POST :id/publish.
 *
 * DTO types transcribe the backend's exercise.saveDraftRequest/versionResponse 1:1
 * (PascalCase, omitempty fields are optional). Normalized* is the read model for the
 * form: every optional field is filled with a concrete default ("", [], null).
 *
 * Key contracts:
 *  - variant.ID is empty for a new variant (backend generates a UUIDv7); EXISTING IDs
 *    must be sent back — the secrets key is (variant ID, device Name, env Name);
 *  - device.ID for NEW devices is generated by the client (crypto.randomUUID()), otherwise
 *    Connections/LinkedDeviceID couldn't reference the device before it's saved;
 *  - Flag: [] → random on deployment; 1 value → fixed;
 *    several → chosen on deployment;
 *  - EnvVar.Value is write-only: empty in responses, HasValue=true if a value
 *    is stored; an empty Value on save means "keep the stored one";
 *  - VisualRender is neither read nor written.
 */
import { apiGet, apiPost, apiPut, apiDelete } from "@/api/client"

const BASE = "/api/exercises"

export type VersionStatus = "draft" | "published" | "unpublished"
export type Difficulty = "trivial" | "easy" | "medium" | "hard" | "insane"
export type DeviceType = "container" | "vm" | "unmanaged-switch" | "hub"
export type IPType = "static" | "dhcp" | "none"
export type EndpointKind = "device" | "vpn" | "internet"
export type Protocol = "http" | "https"
export type PlaceholderKind = "vpn.subnet" | "internet.subnet" | "ip" | "external.link"

/** Lexical JSON (json.RawMessage on the backend) — opaque object. */
export type LexicalDoc = Record<string, unknown>

export type AttachmentDTO = { FileID: string; Name: string }

export type PlaceholderDTO = {
  Kind: PlaceholderKind
  IPReference?: string // "vpn" | "internet" | "static" (only when Kind === "ip")
  Octets1to3?: string // only when IPReference === "static"
  LastOctet?: number // 0..255
  ShowMask?: boolean
  DeviceName?: string // only when Kind === "external.link"
}

export type EnvVarDTO = {
  Name: string
  Value?: string
  Secret: boolean
  HasValue?: boolean // response-only
}

export type ExternalDTO = { Port: number; Protocol: Protocol }

export type IPConfigDTO = {
  Type: IPType
  Addresses?: string[] // CIDR, static only
  Gateway?: string // static only
}

export type InterfaceDTO = { Name: string; MAC?: string; IP: IPConfigDTO }

export type DeviceDTO = {
  ID?: string
  Name: string // DNS label
  Type: DeviceType
  Image?: string
  Interfaces?: InterfaceDTO[]
  EnvVars?: EnvVarDTO[]
  External?: ExternalDTO
}

export type EndpointDTO = { Kind: EndpointKind; DeviceID?: string; Interface?: string }
export type ConnectionDTO = { Endpoints: EndpointDTO[] } // exactly 2
export type NetworkDTO = { Enabled: boolean; DHCP: boolean }

export type TopologyDTO = {
  VPN: NetworkDTO
  Internet: NetworkDTO
  Devices?: DeviceDTO[]
  Connections?: ConnectionDTO[]
  VisualRender?: Record<string, unknown> // reserved, not used
}

export type TaskDTO = {
  ID?: string
  Name: string
  Description?: LexicalDoc | null
  Difficulty: Difficulty
  Flag?: string[]
  LinkedDeviceID?: string
  DeviceFlagVar?: string
  Attachments?: AttachmentDTO[]
  Placeholders?: PlaceholderDTO[]
}

export type VariantDTO = {
  ID?: string
  Index: number // decorative number; identity = ID
  Tasks: TaskDTO[]
  Topology: TopologyDTO
}

export type SaveDraftInput = {
  AdminNote: string
  RegenerateFlagsOnPublish: boolean
  Variants: VariantDTO[]
}

export type VersionListItem = {
  ID: string
  Status: VersionStatus
  AdminNote: string
  VariantCount: number
  CreatedAt: string
  CreatedBy: string | null
  PublishedAt: string | null
}

// ── Normalized read model (every optional field filled) ────────────────────────

export type NormalizedTask = {
  ID: string
  Name: string
  Description: LexicalDoc | null
  Difficulty: Difficulty
  Flag: string[]
  LinkedDeviceID: string
  DeviceFlagVar: string
  Attachments: AttachmentDTO[]
  Placeholders: PlaceholderDTO[]
}

export type NormalizedEnvVar = { Name: string; Value: string; Secret: boolean; HasValue: boolean }

export type NormalizedInterface = {
  Name: string
  MAC: string
  IP: { Type: IPType; Addresses: string[]; Gateway: string }
}

export type NormalizedDevice = {
  ID: string
  Name: string
  Type: DeviceType
  Image: string
  Interfaces: NormalizedInterface[]
  EnvVars: NormalizedEnvVar[]
  External: ExternalDTO | null
}

export type NormalizedEndpoint = { Kind: EndpointKind; DeviceID: string; Interface: string }
export type NormalizedConnection = { Endpoints: NormalizedEndpoint[] }

export type NormalizedTopology = {
  VPN: NetworkDTO
  Internet: NetworkDTO
  Devices: NormalizedDevice[]
  Connections: NormalizedConnection[]
}

export type NormalizedVariant = {
  ID: string
  Index: number
  Tasks: NormalizedTask[]
  Topology: NormalizedTopology
}

export type Version = {
  ID: string
  ExerciseID: string
  Status: VersionStatus
  AdminNote: string
  RegenerateFlagsOnPublish: boolean
  Variants: NormalizedVariant[]
  CreatedAt: string
  CreatedBy: string | null
  PublishedAt: string | null
}

// ── Normalize ──────────────────────────────────────────────────────────────────

function normalizeTask(raw: TaskDTO): NormalizedTask {
  return {
    ID: raw.ID ?? "",
    Name: raw.Name,
    Description: raw.Description ?? null,
    Difficulty: raw.Difficulty,
    Flag: raw.Flag ?? [],
    LinkedDeviceID: raw.LinkedDeviceID ?? "",
    DeviceFlagVar: raw.DeviceFlagVar ?? "",
    Attachments: raw.Attachments ?? [],
    Placeholders: raw.Placeholders ?? [],
  }
}

function normalizeInterface(raw: InterfaceDTO): NormalizedInterface {
  return {
    Name: raw.Name,
    MAC: raw.MAC ?? "",
    IP: {
      Type: raw.IP?.Type ?? "none",
      Addresses: raw.IP?.Addresses ?? [],
      Gateway: raw.IP?.Gateway ?? "",
    },
  }
}

function normalizeDevice(raw: DeviceDTO): NormalizedDevice {
  return {
    ID: raw.ID ?? "",
    Name: raw.Name,
    Type: raw.Type,
    Image: raw.Image ?? "",
    Interfaces: (raw.Interfaces ?? []).map(normalizeInterface),
    EnvVars: (raw.EnvVars ?? []).map((ev) => ({
      Name: ev.Name,
      Value: ev.Value ?? "",
      Secret: ev.Secret,
      HasValue: ev.HasValue ?? false,
    })),
    External: raw.External ?? null,
  }
}

function normalizeTopology(raw: TopologyDTO | null | undefined): NormalizedTopology {
  return {
    VPN: raw?.VPN ?? { Enabled: false, DHCP: false },
    Internet: raw?.Internet ?? { Enabled: false, DHCP: false },
    Devices: (raw?.Devices ?? []).map(normalizeDevice),
    Connections: (raw?.Connections ?? []).map((c) => ({
      Endpoints: (c.Endpoints ?? []).map((ep) => ({
        Kind: ep.Kind,
        DeviceID: ep.DeviceID ?? "",
        Interface: ep.Interface ?? "",
      })),
    })),
  }
}

export function normalizeVariant(raw: VariantDTO): NormalizedVariant {
  return {
    ID: raw.ID ?? "",
    Index: raw.Index,
    Tasks: (raw.Tasks ?? []).map(normalizeTask),
    Topology: normalizeTopology(raw.Topology),
  }
}

type RawVersion = Omit<Version, "Variants"> & { Variants: VariantDTO[] | null }

function normalizeVersion(raw: RawVersion): Version {
  return { ...raw, Variants: (raw.Variants ?? []).map(normalizeVariant) }
}

// ── API ────────────────────────────────────────────────────────────────────────

/** GET /api/exercises/:id/versions */
export async function listVersions(exerciseId: string): Promise<VersionListItem[]> {
  const raw = await apiGet<VersionListItem[] | null>(`${BASE}/${exerciseId}/versions`)
  return raw ?? []
}

/** GET /api/exercises/:id/versions/:versionID */
export async function getVersion(exerciseId: string, versionId: string): Promise<Version> {
  const raw = await apiGet<RawVersion>(`${BASE}/${exerciseId}/versions/${versionId}`)
  return normalizeVersion(raw)
}

/** PUT /api/exercises/:id/draft — full snapshot */
export async function saveDraft(exerciseId: string, input: SaveDraftInput): Promise<Version> {
  const raw = await apiPut<RawVersion>(`${BASE}/${exerciseId}/draft`, input)
  return normalizeVersion(raw)
}

/** POST /api/exercises/:id/publish */
export async function publishDraft(exerciseId: string): Promise<Version> {
  const raw = await apiPost<RawVersion>(`${BASE}/${exerciseId}/publish`, {})
  return normalizeVersion(raw)
}

/** DELETE /api/exercises/:id/draft */
export function discardDraft(exerciseId: string): Promise<void> {
  return apiDelete<void>(`${BASE}/${exerciseId}/draft`)
}

/** POST /api/exercises/:id/versions/:versionID/rollback */
export async function rollbackToVersion(exerciseId: string, versionId: string): Promise<Version> {
  const raw = await apiPost<RawVersion>(`${BASE}/${exerciseId}/versions/${versionId}/rollback`, {})
  return normalizeVersion(raw)
}
